[package]
name        = "capfind-cli"
version     = { workspace = true }
edition     = { workspace = true }
rust-version= { workspace = true }
authors     = { workspace = true }
license     = { workspace = true }
description = "capfind: the CLI entry point"
repository  = { workspace = true }

[[bin]]
name = "capfind"
path = "src/main.rs"

[dependencies]
capfind-core    = { workspace = true }
capfind-parsers = { workspace = true }
capfind-search  = { workspace = true }

clap               = { workspace = true }
clap_complete      = { workspace = true }
owo-colors         = { workspace = true }
is-terminal        = { workspace = true }
anyhow             = { workspace = true }
thiserror          = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
ignore             = { workspace = true }
rayon              = { workspace = true }
memmap2            = { workspace = true }
crossbeam-channel  = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }

[dev-dependencies]
assert_cmd        = { workspace = true }
predicates        = { workspace = true }
tempfile          = { workspace = true }
pretty_assertions = { workspace = true }
